# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/migueldoctor/SpringCloudConfig-GitRepository

  # Spring properties
  profiles:
    active: dev